rails/config/routes.rb
Rails.application.routes.draw do
  resources :data
  resources :babies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



 root to: 'babies#index'

end

rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/app/models/baby.rb
class Baby < ApplicationRecord
	
end

rails/app/models/datum.rb
class Datum < ApplicationRecord
end

rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

rails/app/controllers/babies_controller.rb
class BabiesController < ApplicationController
  before_action :set_baby, only: [:show, :edit, :update, :destroy]
require 'net/http'
require 'json'

  # GET /babies
  # GET /babies.json
  def index
    @babies = Baby.all
  end

  # GET /babies/1
  # GET /babies/1.json
  def show
    @baby = Baby.find(params[:id])
  end

  # GET /babies/new
  def new
    @baby = Baby.new
  end

  # GET /babies/1/edit
  def edit
  end

  # POST /babies
  # POST /babies.json
  def create

    @baby = Baby.new(baby_params)


    respond_to do |format|
      if @baby.save

        @dadada = Baby.first
          if @baby.nota_type == 'type_1'
            @dadada.team_1 += 1;
          elsif @baby.nota_type == 'type_2'
            @dadada.team_2 += 1;
          elsif @baby.nota_type == 'type_3'
            @dadada.team_3 += 1;
          elsif @baby.nota_type == 'type_4'
            @dadada.team_4 += 1;
          end
          @dadada.save

           @dadada2 = Baby.first
          if @baby.start_status == 'team_1'
            @dadada2.start_1 = true
          elsif @baby.start_status == 'team_2'
            @dadada2.start_2 = true
          elsif @baby.start_status == 'team_3'
            @dadada2.start_3 = true
          elsif @baby.start_status == 'team_4'
            @dadada2.start_4 = true
          end
          @dadada2.save


        format.html { redirect_to @baby, notice: 'Baby was successfully created.' }
        format.json { render :show, status: :created, location: @baby }
      else
        format.html { render :new }
        format.json { render json: @baby.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /babies/1
  # PATCH/PUT /babies/1.json
  def update
    respond_to do |format|
      if @baby.update(baby_params)
        format.html { redirect_to @baby, notice: 'Baby was successfully updated.' }
        format.json { render :show, status: :ok, location: @baby }
      else
        format.html { render :edit }
        format.json { render json: @baby.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /babies/1
  # DELETE /babies/1.json
  def destroy
    @baby.destroy
    respond_to do |format|
      format.html { redirect_to babies_url, notice: 'Baby was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_baby
      @baby = Baby.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def baby_params

      params.fetch(:baby, {})
      params.permit(:nota_type,:start_status)
    end

end

rails/app/controllers/data_controller.rb
class DataController < ApplicationController
  before_action :set_datum, only: [:show, :edit, :update, :destroy]

  # GET /data
  # GET /data.json
  def index
    @data = Datum.all
  end

  # GET /data/1
  # GET /data/1.json
  def show
  end

  # GET /data/new
  def new
    @datum = Datum.new
  end

  # GET /data/1/edit
  def edit
  end

  # POST /data
  # POST /data.json
  def create
    @datum = Datum.new(datum_params)

    respond_to do |format|
      if @datum.save
        format.html { redirect_to @datum, notice: 'Datum was successfully created.' }
        format.json { render :show, status: :created, location: @datum }
      else
        format.html { render :new }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data/1
  # PATCH/PUT /data/1.json
  def update
    respond_to do |format|
      if @datum.update(datum_params)
        format.html { redirect_to @datum, notice: 'Datum was successfully updated.' }
        format.json { render :show, status: :ok, location: @datum }
      else
        format.html { render :edit }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data/1
  # DELETE /data/1.json
  def destroy
    @datum.destroy
    respond_to do |format|
      format.html { redirect_to data_url, notice: 'Datum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_datum
      @datum = Datum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def datum_params
      params.require(:datum).permit(:team_1, :team_2, :team_3, :team_4)
    end
end

rails/app/controllers/nota_controller.rb
class NotaController < ApplicationController
  before_action :set_notum, only: [:show, :edit, :update, :destroy]

  # GET /nota
  # GET /nota.json
  def index
    @nota = Notum.all
  end

  # GET /nota/1
  # GET /nota/1.json
  def show
  end

  # GET /nota/new
  def new
    @notum = Notum.new
  end

  # GET /nota/1/edit
  def edit
  end

  # POST /nota
  # POST /nota.json
  def create
    @notum = Notum.new(notum_params)

    respond_to do |format|
      if @notum.save
        format.html { redirect_to @notum, notice: 'Notum was successfully created.' }
        format.json { render :show, status: :created, location: @notum }
      else
        format.html { render :new }
        format.json { render json: @notum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nota/1
  # PATCH/PUT /nota/1.json
  def update
    respond_to do |format|
      if @notum.update(notum_params)
        format.html { redirect_to @notum, notice: 'Notum was successfully updated.' }
        format.json { render :show, status: :ok, location: @notum }
      else
        format.html { render :edit }
        format.json { render json: @notum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nota/1
  # DELETE /nota/1.json
  def destroy
    @notum.destroy
    respond_to do |format|
      format.html { redirect_to nota_url, notice: 'Notum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notum
      @notum = Notum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notum_params
      params.require(:notum).permit(:team_1, :team_2, :team_3, :team_4, :start_1, :start_2, :start_3, :start_4)
    end
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/app/helpers/babies_helper.rb
module BabiesHelper
end

rails/app/helpers/data_helper.rb
module DataHelper
end

rails/app/views/babies/_form.html.erb
<%= form_for(baby) do |f| %>
  <% if baby.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(baby.errors.count, "error") %> prohibited this baby from being saved:</h2>

      <ul>
      <% baby.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/app/views/babies/edit.html.erb
<h1>Editing Baby</h1>

<%= render 'form', baby: @baby %>

<%= link_to 'Show', @baby %> |
<%= link_to 'Back', babies_path %>

rails/app/views/babies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Babies</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @babies.each do |baby| %>
      <tr>
        <td><%= baby.nota_type%></td>
        <td><%= baby.team_1 %></td>
        <td><%= baby.team_2 %></td>
        <td><%= baby.team_3 %></td>
        <td><%= baby.team_4 %></td>
        <td><%= baby.nota_type%></td>
        <td><%= baby.start_1 %></td>
        <td><%= baby.start_2 %></td>
        <td><%= baby.start_3 %></td>
        <td><%= baby.start_4 %></td>
        <td><%= link_to 'Show', baby %></td>
        <td><%= link_to 'Edit', edit_baby_path(baby) %></td>
        <td><%= link_to 'Destroy', baby, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Baby', new_baby_path %>

rails/app/views/babies/new.html.erb
<h1>New Baby</h1>

<%= render 'form', baby: @baby %>

<%= link_to 'Back', babies_path %>

rails/app/views/babies/show.html.erb
<p id="notice"><%= notice %></p>

<%= @baby.nota_type%>

<%= link_to 'Edit', edit_baby_path(@baby) %> |
<%= link_to 'Back', babies_path %>

rails/app/views/data/_form.html.erb
<%= form_for(datum) do |f| %>
  <% if datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(datum.errors.count, "error") %> prohibited this datum from being saved:</h2>

      <ul>
      <% datum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :team_1 %>
    <%= f.number_field :team_1 %>
  </div>

  <div class="field">
    <%= f.label :team_2 %>
    <%= f.number_field :team_2 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/app/views/data/edit.html.erb
<h1>Editing Datum</h1>

<%= render 'form', datum: @datum %>

<%= link_to 'Show', @datum %> |
<%= link_to 'Back', data_path %>

rails/app/views/data/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Data</h1>

<table>
  <thead>
    <tr>
      <th>Team 1</th>
      <th>Team 2</th>
      <th>Team 3</th>
      <th>Team 4</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data.each do |datum| %>
      <tr>
        <td><%= datum.team_1 %></td>
        <td><%= datum.team_2 %></td>
        <td><%= datum.team_3 %></td>
        <td><%= datum.team_4 %></td>
        <td><%= link_to 'Show', datum %></td>
        <td><%= link_to 'Edit', edit_datum_path(datum) %></td>
        <td><%= link_to 'Destroy', datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Datum', new_datum_path %>

rails/app/views/data/new.html.erb
<h1>New Datum</h1>

<%= render 'form', datum: @datum %>

<%= link_to 'Back', data_path %>

rails/app/views/data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team 1:</strong>
  <%= @datum.team_1 %>
</p>

<p>
  <strong>Team 2:</strong>
  <%= @datum.team_2 %>
</p>

<%= link_to 'Edit', edit_datum_path(@datum) %> |
<%= link_to 'Back', data_path %>

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meshapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>